Repository CS3219-AY2324S1/ay2324s1-course-assessment-g34, pull requests merged in 2023-10, with the labels that each got.

#33 Add matching service
  matching-service/.dockerignore
  matching-service/.gitignore
  matching-service/Dockerfile
  matching-service/README.md
  matching-service/docker-compose.yml
  matching-service/index.html
  matching-service/package.json
  matching-service/server.js
Labels: type: feature, priority: high

#36 [Frontend] Implement authentication and authorisation + integration
  .DS_Store
  .gitignore
  .vscode/settings.json
  docker-compose.yml
  frontend/.eslintrc.json
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ComponentGuard.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/QuestionPage/AddQuestion.jsx
  frontend/src/components/QuestionPage/EditQuestion.jsx
  frontend/src/components/QuestionPage/QuestionForm.jsx
  frontend/src/components/QuestionPage/QuestionRow.jsx
  frontend/src/components/QuestionPage/QuestionTable.jsx
  frontend/src/components/RouteGuard.jsx
  frontend/src/components/SolidButton.js
  frontend/src/config/uris.js
  frontend/src/contexts/AuthContext.jsx
  frontend/src/hooks/useAuth.js
  frontend/src/pages/_app.jsx
  frontend/src/pages/index.jsx
  frontend/src/pages/login.jsx
  frontend/src/pages/questions.jsx
  frontend/src/pages/signup.jsx
  frontend/src/utils/constants.js
  frontend/src/utils/validation.js
  index.html
  question-service/Dockerfile
  question-service/README.md
  question-service/docker-compose.yml
  question-service/index.js
  question-service/package.json
  question-service/routes/routes.js
  user_service/README.md
  user_service/docker-compose.yml
  user_service/requirements.txt
  user_service/user_service/settings.py
Labels: type: feature, type: enhancement, priority: high

#50 [Question-Service] Filter, sort and get random question
  question-service/README.md
  question-service/routes/routes.js
Labels: type: enhancement, priority: medium

#57 [Matching Service] Add session id once 2 users are matched
  matching-service/index.html
  matching-service/package.json
  matching-service/server.js
Labels: type: chore, priority: high

#66 [Question service] Refactored to use MVC pattern
  question-service/controllers/questionController.js
  question-service/index.js
  question-service/routes/questionRoutes.js
  question-service/routes/routes.js
  question-service/services/questionService.js
Labels: type: chore

#56 [Frontend, Collab Service, Matching Service] Collaboration Page UI with Socket.IO and Redux Integration
  collab-service/.eslintrc.json
  collab-service/Dockerfile
  collab-service/README.md
  collab-service/constants/events.js
  collab-service/constants/uris.js
  collab-service/dto/createSessionDto.js
  collab-service/eventHandlers/sessionHandler.js
  collab-service/package-lock.json
  collab-service/package.json
  collab-service/server.js
  collab-service/utils/api.js
  collab-service/utils/dbUtils.js
  collab-service/utils/eventEmitters.js
  collab-service/utils/socket.js
  docker-compose.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/store.js
  frontend/src/components/CollabPage/CollabEditor.jsx
  frontend/src/components/CollabPage/CollabPage.jsx
  frontend/src/components/CollabPage/ConfirmEndModal.jsx
  frontend/src/components/CollabPage/EditorPanel.jsx
  frontend/src/components/CollabPage/LeaveSessionModal.jsx
  frontend/src/components/CollabPage/QuestionPanel.jsx
  frontend/src/components/DifficultyChip.jsx
  frontend/src/components/MatchPage/MatchModal.jsx
  frontend/src/components/QuestionPage/QuestionRow.jsx
  frontend/src/config/uris.js
  frontend/src/features/match/matchSlice.js
  frontend/src/features/session/sessionSlice.js
  frontend/src/pages/_app.jsx
  frontend/src/pages/collab.jsx
  frontend/src/pages/match.jsx
  frontend/src/theme.js
  frontend/src/utils/constants.js
  frontend/src/utils/eventEmitters.js
  frontend/src/utils/eventHandlers.js
  frontend/src/utils/socketUtils.js
  matching-service/constants/events.js
  matching-service/eventHandlers/matchHandler.js
  matching-service/eventHandlers/sessionHandler.js
  matching-service/package.json
  matching-service/server.js
  matching-service/utils/queueService.js
  matching-service/utils/socket.js
  matching-service/utils/timeoutService.js
  matching-service/utils/utils.js
  question-service/controllers/questionController.js
  question-service/routes/questionRoutes.js
  question-service/services/questionService.js
Labels: type: feature, priority: high
